# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'testYYKit' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
	pod 'YYKit'

end
