# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyZhihuDaily' do
  
	pod 'ViewDeck';
	pod 'AFNetworking';
	pod 'SDWebImage';
	pod 'YYModel';
	pod 'Mantle';
end
