# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Test_ZhihuDaily' do
  pod 'AFNetworking';
  pod 'YYModel';
  pod 'MBProgressHUD';
  pod 'SDWebImage';
  pod 'TOWebViewController';
  pod 'MMDrawerController';
  pod 'ViewDeck';
end
